### ISSUE TITLE
Is a illness lemon unhealthy

### ISSUE THREAD

**Issue by leenpluto** [jordan-bird/synthetic-fruit-image-generator#1]
i see unhealthy lemon only contains mould, gangrene and dark_style_remains. Are illness lemons classified as healthy.

**Comment by jordan-bird** [comment]
Hi @leenpluto,

If you check the original dataset's COCO segmentations then you'll see that many illness segments are infact gangreneous and/or mouldy/dark style, I chose to discard the illness class since one of the other three were also present in the vast majority of cases and so would constitute directly towards the binary classification of 'healthy' versus 'unhealthy' that this project faced. This, along with our results in the paper mentioned argue towards a generalisation ability when lemons are unhealthy or otherwise.

If I have some time then I will aim towards updating the dataset's segmentations in the form of a pull request to [the original dataset](https://github.com/softwaremill/lemon-dataset) - but, that said, and as our and their results show, the dataset is already very good so that might not even really be needed for some impactful autonomous agriculture projects!

**Comment by jordan-bird** [comment]
In most cases an illness on a lemon is only 2-3 pixels in size at the full 1056x1056 resolution. When resized to 256px these artifacts effectively all disappear and so they were not considered. If someone wants to train a new CGAN at a higher resolution to include these artifacts then the dataset entry would be `img_path/img,0,1,0,0,0,0,0,0,0` for this class (specifically `1` in the second column).

At 256px these images would almost all show healthy lemons and would just confuse the CGAN since there would be no major discernible features at this point. Any lemon with an illness where any of the other negative traits are considered are thus considered as unhealthy.

Example: 

0004_A_H_15_A.jpg at 256px:
![0004_A_H_15_A_256px](https://i.imgur.com/iy6Ftnl.jpg)

0004_A_H_15_A.jpg at full resolution:
![0004_A_H_15_A](https://i.imgur.com/3FDsKkN.jpg)
